djangoTODO/TODO/urls.py
from django.urls import path
from . import views
from .views import TaskList as TaskListView
from .views import CreateTask as CreateTaskView


urlpatterns = [    
    path('', TaskListView.as_view(),name='TODO-POSTS' ),
    path('new/', CreateTaskView.as_view(),name='TODO-CREATE' ),
]

djangoTODO/djangoTODO/urls.py
from django.contrib import admin
from django.urls import path
from django.urls import include

urlpatterns = [
    path('', include('TODO.urls') ),
    path('admin/', admin.site.urls),
]

djangoTODO/TODO/models.py
from django.db import models
from django.utils import timezone
from django.urls import reverse

# Create your models here.


class Task(models.Model):
    contex=models.CharField(max_length=255)
    title=models.CharField(max_length=30)
    date=models.DateTimeField(default=timezone.now)
    zrobione=models.BooleanField(default=True)
    
    def __str__(self)->str:
        return self.title

    def get_absolute_url(self):
        return reverse('TODO-POSTS')    

djangoTODO/TODO/forms.py
from django import forms

class AddTASK(forms.Form):
    title = forms.CharField(label='taks title', max_length=100)
    contex = forms.CharField(label='task contex', max_length=255)

djangoTODO/TODO/views.py
from django.shortcuts import render
from django.views.generic import ListView,CreateView
from .models import Task
# Create your views here.



class TaskList(ListView):
    model=Task
    
 

class CreateTask(CreateView):
   model=Task
   fields=['title','contex'] 

djangoTODO/TODO/templates/TODO/Task_form.html
{%extends "TODO/base.html"%}
{% load crispy_forms_tags %}
{%block content%}

<div class="content-section">
    <form method="POST">
        {% csrf_token %}
        <fieldset class="form-group">
            <legend class="border-bottom mb-4">Blog Post</legend>
            {{ form|crispy }}
        </fieldset>
        <div class="form-group">
            <button class="btn btn-outline-info" type="submit">Post</button>
        </div>
    </form>       
</div>


{%endblock content%}

djangoTODO/TODO/templates/TODO/Task_list.html
{%extends "TODO/base.html"%}
{%block content%}

{% for task in task_list%}
<div class="card tlo">
  <div class="card-header">
    {{task.date}}
  </div>
  <div class="card-body">
    <h4 class="card-title">{{task.title}}</h4>
    <p class="card-text">{{task.contex}}</p>
    <a href="#" class="btn btn-primary">{{task.zrobione}}</a>          
  </div>
</div>    
{%endfor%}


{%endblock content%}

djangoTODO/TODO/templates/TODO/base.html
{%load static%}

<!doctype html>
<html lang="en">
  <head>    
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">    
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/css/bootstrap.min.css" integrity="sha384-TX8t27EcRE3e/ihU7zmQxVncDAy5uIKz4rEkgIXeMed4M0jlfIDPvg6uqKI2xXr2" crossorigin="anonymous">
    <link rel="stylesheet" type="text/css" href="{% static 'TODO/main.css' %}">    
    <title>ToDo App</title>
  </head>

  <body class="tlo">

    <nav class="navbar navbar-expand-lg navbar-light bg-light tlo row justify-content-md-center">
        <a class="navbar-brand" href="{%url 'TODO-POSTS' %}">DjangoTODO</a>      
        <a class="navbar-brand" href="{%url 'TODO-CREATE' %}">Dodaj</a>      
    </nav>

    {% block content %}{% endblock %}

    

    
    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ho+j7jyWK8fNQe+A12Hb8AhRq26LrZ/JpcUGGOn+Y7RsweNrtN/tE3MoK7ZeZDyx" crossorigin="anonymous"></script>
  </body>
</html>